//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_HRMSEntities : DbContext
    {
        public DB_HRMSEntities()
            : base("name=DB_HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Emp_Credential> Tbl_Emp_Credential { get; set; }
        public virtual DbSet<tbl_Employee_Docs> tbl_Employee_Docs { get; set; }
        public virtual DbSet<tbl_Employee_Registration> tbl_Employee_Registration { get; set; }
        public virtual DbSet<Tbl_Master_Designation> Tbl_Master_Designation { get; set; }
        public virtual DbSet<Tbl_Master_District> Tbl_Master_District { get; set; }
        public virtual DbSet<Tbl_Master_Mandal> Tbl_Master_Mandal { get; set; }
        public virtual DbSet<Tbl_Master_Pariyojana> Tbl_Master_Pariyojana { get; set; }
        public virtual DbSet<tbl_Master_Salary> tbl_Master_Salary { get; set; }
        public virtual DbSet<Tbl_Master_Yojana_Designation_Salary> Tbl_Master_Yojana_Designation_Salary { get; set; }
        public virtual DbSet<Tbl_Notice> Tbl_Notice { get; set; }
        public virtual DbSet<tbl_UserDetail> tbl_UserDetail { get; set; }
    
        public virtual int BackupDatabase(string databaseName, string backupPath)
        {
            var databaseNameParameter = databaseName != null ?
                new ObjectParameter("databaseName", databaseName) :
                new ObjectParameter("databaseName", typeof(string));
    
            var backupPathParameter = backupPath != null ?
                new ObjectParameter("backupPath", backupPath) :
                new ObjectParameter("backupPath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BackupDatabase", databaseNameParameter, backupPathParameter);
        }
    
        public virtual ObjectResult<Emp_Login_Result> Emp_Login(string emp_Code, string emp_Password)
        {
            var emp_CodeParameter = emp_Code != null ?
                new ObjectParameter("Emp_Code", emp_Code) :
                new ObjectParameter("Emp_Code", typeof(string));
    
            var emp_PasswordParameter = emp_Password != null ?
                new ObjectParameter("Emp_Password", emp_Password) :
                new ObjectParameter("Emp_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Emp_Login_Result>("Emp_Login", emp_CodeParameter, emp_PasswordParameter);
        }
    
        public virtual ObjectResult<Proc_DownloadSlip_Result> Proc_DownloadSlip(Nullable<int> pk_Emp_id)
        {
            var pk_Emp_idParameter = pk_Emp_id.HasValue ?
                new ObjectParameter("pk_Emp_id", pk_Emp_id) :
                new ObjectParameter("pk_Emp_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_DownloadSlip_Result>("Proc_DownloadSlip", pk_Emp_idParameter);
        }
    
        public virtual int Proc_Notice(string path, string name, string notice_Type, string fk_MAndal_id, string fk_Emp_id)
        {
            var pathParameter = path != null ?
                new ObjectParameter("path", path) :
                new ObjectParameter("path", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var notice_TypeParameter = notice_Type != null ?
                new ObjectParameter("Notice_Type", notice_Type) :
                new ObjectParameter("Notice_Type", typeof(string));
    
            var fk_MAndal_idParameter = fk_MAndal_id != null ?
                new ObjectParameter("Fk_MAndal_id", fk_MAndal_id) :
                new ObjectParameter("Fk_MAndal_id", typeof(string));
    
            var fk_Emp_idParameter = fk_Emp_id != null ?
                new ObjectParameter("Fk_Emp_id", fk_Emp_id) :
                new ObjectParameter("Fk_Emp_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Notice", pathParameter, nameParameter, notice_TypeParameter, fk_MAndal_idParameter, fk_Emp_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_Verify_doc_Admin(string emp_code)
        {
            var emp_codeParameter = emp_code != null ?
                new ObjectParameter("Emp_code", emp_code) :
                new ObjectParameter("Emp_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_Verify_doc_Admin", emp_codeParameter);
        }
    
        public virtual ObjectResult<SP_DIST_PARIYOJANA_REG_DOC_COUNT_Result> SP_DIST_PARIYOJANA_REG_DOC_COUNT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DIST_PARIYOJANA_REG_DOC_COUNT_Result>("SP_DIST_PARIYOJANA_REG_DOC_COUNT");
        }
    
        public virtual ObjectResult<sp_District_Pariyojana_RegType_Count_Report_Result> sp_District_Pariyojana_RegType_Count_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_District_Pariyojana_RegType_Count_Report_Result>("sp_District_Pariyojana_RegType_Count_Report");
        }
    
        public virtual ObjectResult<Sp_Emp_Reg_Result> Sp_Emp_Reg(Nullable<int> fk_Mandal_id, string mandal_Name, Nullable<int> fk_Dist_Id, string district_Name, Nullable<int> pk_Designation_ID, Nullable<int> pk_Pariyojana_ID, string salary, string emp_post_Add, string postal_Code, string emp_Name, string f_Name, Nullable<System.DateTime> dOB, string address, string mobile_No, string alternate_Mob_No, string aadhar_No, string gender, string pAN_NO, string email_id, string sPR_NO, string emp_Category, string sub_category, string bank_Name, string account_No, string iFSC_Code, string branch_Name, string uAN_No, string eSIC_No, string nationality, string corres_Address, string city, string state, string country, string physically_Challenged, string territory, Nullable<int> exp_In_Yrs, Nullable<System.DateTime> created_date, string identification_Id, string registration_Type)
        {
            var fk_Mandal_idParameter = fk_Mandal_id.HasValue ?
                new ObjectParameter("fk_Mandal_id", fk_Mandal_id) :
                new ObjectParameter("fk_Mandal_id", typeof(int));
    
            var mandal_NameParameter = mandal_Name != null ?
                new ObjectParameter("Mandal_Name", mandal_Name) :
                new ObjectParameter("Mandal_Name", typeof(string));
    
            var fk_Dist_IdParameter = fk_Dist_Id.HasValue ?
                new ObjectParameter("fk_Dist_Id", fk_Dist_Id) :
                new ObjectParameter("fk_Dist_Id", typeof(int));
    
            var district_NameParameter = district_Name != null ?
                new ObjectParameter("District_Name", district_Name) :
                new ObjectParameter("District_Name", typeof(string));
    
            var pk_Designation_IDParameter = pk_Designation_ID.HasValue ?
                new ObjectParameter("pk_Designation_ID", pk_Designation_ID) :
                new ObjectParameter("pk_Designation_ID", typeof(int));
    
            var pk_Pariyojana_IDParameter = pk_Pariyojana_ID.HasValue ?
                new ObjectParameter("pk_Pariyojana_ID", pk_Pariyojana_ID) :
                new ObjectParameter("pk_Pariyojana_ID", typeof(int));
    
            var salaryParameter = salary != null ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(string));
    
            var emp_post_AddParameter = emp_post_Add != null ?
                new ObjectParameter("Emp_post_Add", emp_post_Add) :
                new ObjectParameter("Emp_post_Add", typeof(string));
    
            var postal_CodeParameter = postal_Code != null ?
                new ObjectParameter("Postal_Code", postal_Code) :
                new ObjectParameter("Postal_Code", typeof(string));
    
            var emp_NameParameter = emp_Name != null ?
                new ObjectParameter("Emp_Name", emp_Name) :
                new ObjectParameter("Emp_Name", typeof(string));
    
            var f_NameParameter = f_Name != null ?
                new ObjectParameter("F_Name", f_Name) :
                new ObjectParameter("F_Name", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var mobile_NoParameter = mobile_No != null ?
                new ObjectParameter("Mobile_No", mobile_No) :
                new ObjectParameter("Mobile_No", typeof(string));
    
            var alternate_Mob_NoParameter = alternate_Mob_No != null ?
                new ObjectParameter("Alternate_Mob_No", alternate_Mob_No) :
                new ObjectParameter("Alternate_Mob_No", typeof(string));
    
            var aadhar_NoParameter = aadhar_No != null ?
                new ObjectParameter("Aadhar_No", aadhar_No) :
                new ObjectParameter("Aadhar_No", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var pAN_NOParameter = pAN_NO != null ?
                new ObjectParameter("PAN_NO", pAN_NO) :
                new ObjectParameter("PAN_NO", typeof(string));
    
            var email_idParameter = email_id != null ?
                new ObjectParameter("Email_id", email_id) :
                new ObjectParameter("Email_id", typeof(string));
    
            var sPR_NOParameter = sPR_NO != null ?
                new ObjectParameter("SPR_NO", sPR_NO) :
                new ObjectParameter("SPR_NO", typeof(string));
    
            var emp_CategoryParameter = emp_Category != null ?
                new ObjectParameter("Emp_Category", emp_Category) :
                new ObjectParameter("Emp_Category", typeof(string));
    
            var sub_categoryParameter = sub_category != null ?
                new ObjectParameter("Sub_category", sub_category) :
                new ObjectParameter("Sub_category", typeof(string));
    
            var bank_NameParameter = bank_Name != null ?
                new ObjectParameter("Bank_Name", bank_Name) :
                new ObjectParameter("Bank_Name", typeof(string));
    
            var account_NoParameter = account_No != null ?
                new ObjectParameter("Account_No", account_No) :
                new ObjectParameter("Account_No", typeof(string));
    
            var iFSC_CodeParameter = iFSC_Code != null ?
                new ObjectParameter("IFSC_Code", iFSC_Code) :
                new ObjectParameter("IFSC_Code", typeof(string));
    
            var branch_NameParameter = branch_Name != null ?
                new ObjectParameter("Branch_Name", branch_Name) :
                new ObjectParameter("Branch_Name", typeof(string));
    
            var uAN_NoParameter = uAN_No != null ?
                new ObjectParameter("UAN_No", uAN_No) :
                new ObjectParameter("UAN_No", typeof(string));
    
            var eSIC_NoParameter = eSIC_No != null ?
                new ObjectParameter("ESIC_No", eSIC_No) :
                new ObjectParameter("ESIC_No", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(string));
    
            var corres_AddressParameter = corres_Address != null ?
                new ObjectParameter("Corres_Address", corres_Address) :
                new ObjectParameter("Corres_Address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var physically_ChallengedParameter = physically_Challenged != null ?
                new ObjectParameter("Physically_Challenged", physically_Challenged) :
                new ObjectParameter("Physically_Challenged", typeof(string));
    
            var territoryParameter = territory != null ?
                new ObjectParameter("Territory", territory) :
                new ObjectParameter("Territory", typeof(string));
    
            var exp_In_YrsParameter = exp_In_Yrs.HasValue ?
                new ObjectParameter("Exp_In_Yrs", exp_In_Yrs) :
                new ObjectParameter("Exp_In_Yrs", typeof(int));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("Created_date", created_date) :
                new ObjectParameter("Created_date", typeof(System.DateTime));
    
            var identification_IdParameter = identification_Id != null ?
                new ObjectParameter("Identification_Id", identification_Id) :
                new ObjectParameter("Identification_Id", typeof(string));
    
            var registration_TypeParameter = registration_Type != null ?
                new ObjectParameter("Registration_Type", registration_Type) :
                new ObjectParameter("Registration_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Emp_Reg_Result>("Sp_Emp_Reg", fk_Mandal_idParameter, mandal_NameParameter, fk_Dist_IdParameter, district_NameParameter, pk_Designation_IDParameter, pk_Pariyojana_IDParameter, salaryParameter, emp_post_AddParameter, postal_CodeParameter, emp_NameParameter, f_NameParameter, dOBParameter, addressParameter, mobile_NoParameter, alternate_Mob_NoParameter, aadhar_NoParameter, genderParameter, pAN_NOParameter, email_idParameter, sPR_NOParameter, emp_CategoryParameter, sub_categoryParameter, bank_NameParameter, account_NoParameter, iFSC_CodeParameter, branch_NameParameter, uAN_NoParameter, eSIC_NoParameter, nationalityParameter, corres_AddressParameter, cityParameter, stateParameter, countryParameter, physically_ChallengedParameter, territoryParameter, exp_In_YrsParameter, created_dateParameter, identification_IdParameter, registration_TypeParameter);
        }
    
        public virtual ObjectResult<SP_REG_WISE_DOC_COUNT_Result> SP_REG_WISE_DOC_COUNT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REG_WISE_DOC_COUNT_Result>("SP_REG_WISE_DOC_COUNT");
        }
    
        public virtual ObjectResult<SP_REG_WISE_DOC_COUNT_FILTER_Result> SP_REG_WISE_DOC_COUNT_FILTER(Nullable<int> fk_Mandal_id, Nullable<int> fk_Dist_id)
        {
            var fk_Mandal_idParameter = fk_Mandal_id.HasValue ?
                new ObjectParameter("fk_Mandal_id", fk_Mandal_id) :
                new ObjectParameter("fk_Mandal_id", typeof(int));
    
            var fk_Dist_idParameter = fk_Dist_id.HasValue ?
                new ObjectParameter("fk_Dist_id", fk_Dist_id) :
                new ObjectParameter("fk_Dist_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REG_WISE_DOC_COUNT_FILTER_Result>("SP_REG_WISE_DOC_COUNT_FILTER", fk_Mandal_idParameter, fk_Dist_idParameter);
        }
    
        public virtual ObjectResult<SP_REPORT_VERIFIED_COUNT_Result> SP_REPORT_VERIFIED_COUNT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORT_VERIFIED_COUNT_Result>("SP_REPORT_VERIFIED_COUNT");
        }
    }
}
