//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Master_Yojana_Designation_Salary
    {
        public int pk__des_id { get; set; }
        public string Mandal_Name { get; set; }
        public Nullable<int> fk_Mandal_id { get; set; }
        public string District_Name { get; set; }
        public Nullable<int> fk_District_id { get; set; }
        public Nullable<int> fk_Pariyojana_Id { get; set; }
        public string Pariyojana_Name { get; set; }
        public string Pariyojana_Code { get; set; }
        public Nullable<int> fk_Designation_Id { get; set; }
        public string Designations_Name { get; set; }
        public string Designations_Code { get; set; }
        public string Salary { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
