//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Emp_Credential
    {
        public int Pk_ID { get; set; }
        public Nullable<int> Fk_Emp_Id { get; set; }
        public string Emp_Code { get; set; }
        public string Emp_Mail_Id { get; set; }
        public string Emp_Id { get; set; }
        public string Emp_Password { get; set; }
        public string OldPassword { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public string Is_OTP { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Verify_Status { get; set; }
    }
}
