//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notice
    {
        public int PK_Notice_ID { get; set; }
        public string Notice_Type { get; set; }
        public string Notice_Path { get; set; }
        public string Notice_Name { get; set; }
        public Nullable<long> Fk_Emp_id { get; set; }
        public string Fk_Mandal_id { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
