//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Docs
    {
        public int pk_Doc_Id { get; set; }
        public Nullable<int> fk_Emp_Id { get; set; }
        public string Emp_Code { get; set; }
        public string Doc_Type { get; set; }
        public string Doc_Name { get; set; }
        public string Doc_Id { get; set; }
        public string Doc_Sr_No { get; set; }
        public string Doc_Path { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string created_IP { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Verify_Status { get; set; }
        public Nullable<System.DateTime> Verify_Date { get; set; }
        public string Verify_Remark { get; set; }
        public string verified_By { get; set; }
        public string Verify_IP { get; set; }
    }
}
