//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Master_Salary
    {
        public int pk_Salary_id { get; set; }
        public Nullable<long> Salary { get; set; }
        public Nullable<bool> is_Active { get; set; }
    }
}
