//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Master_Designation
    {
        public int pk_Designation_id { get; set; }
        public string Designation_Code { get; set; }
        public string Designation { get; set; }
        public Nullable<int> fk_Pariyojana_Id { get; set; }
        public string Pariyojana_Code { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
