//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Master_Pariyojana
    {
        public int pk__Pariyojana_Id { get; set; }
        public string Pariyojana_Code { get; set; }
        public string Pariyojana { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
