//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Master_Mandal
    {
        public int pk_id { get; set; }
        public string Mandal_Name { get; set; }
        public string Mandal_Code { get; set; }
        public string Feild_1 { get; set; }
    }
}
